version: '3.8'

services:
  lumia_app:
    build: .
    container_name: lumia_app_container
    ports:
      - "8000:8000"
    volumes:
      - ./db:/app/db
    depends_on:
      - ollama  # Garante que a API LLM esteja disponível
    restart: unless-stopped

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"  # Porta da API REST local da LLM
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

volumes:
  ollama_data:
