version: '3.8'

services:
  lumia_backend:
    build: .
    container_name: lumia_backend_container
    ports:
      - "8000:8000"
    volumes:
      - ./db:/app/db
    restart: unless-stopped
    networks:
      - lumia_network

  lumia_frontend:
    build: .
    container_name: lumia_frontend_container
    ports:
      - "8501:8501"
    command: streamlit run app.py --server.port 8501 --server.address 0.0.0.0
    volumes:
      - ./db:/app/db
    depends_on:
      - lumia_backend
    restart: unless-stopped
    networks:
      - lumia_network

networks:
  lumia_network:
    driver: bridge
